Server:
  Listen: :18080
  Env: Dev

Database:
  Driver: mysql
  Mysql:
    HostPort: tcp(***:3306)
    UserPassword: root:****
    DB: demo
  Conn:
    MaxLifeTime: 600
    MaxIdle: 10
    MaxOpen: 80
    PerOpTimeout: 3

